language: cpp
compiler:
  - gcc
  - clang
before_install:
  - python setup.py
  - sudo apt-get update
  - if test $CC = gcc; then sudo apt-get install gcc-4.7 g++-4.7; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 20; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 20; fi
  - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
  - if test $CC = gcc; then sudo update-alternatives --config g++; fi
script: scons
